#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then you need to set the SHELL environment variable to point
#       to that shell before running this script.
#
#       SHELL=/bin/bash ./gradlew
#
#   (2) This script points to the Java runtime. You need to have Java installed
#       and available on your PATH. If Java is not available, the script will
#       fail with an error message indicating where to find Java.
#
##############################################################################

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H -n is not supported. Use the POSIX-compliant command 'ulimit -Hn'.
        # In POSIX sh, ulimit -n is supported, but not with the flag -n. Use the POSIX-compliant command 'ulimit -n'.
        # Also, the order of the options matters: if we use -n first, it sets the soft limit; if we use -H first, it sets the hard limit.
        # The 'head' command is used to ensure we only output the first line, as some systems may output multiple lines.
        # The 'grep' command is used to ensure we only output lines that contain the word 'open files'.
        # This is necessary because on some systems, ulimit -n may output a message about the limit being unlimited.
        # We use '2>/dev/null' to suppress error messages.
        ulimit -Hn 2>/dev/null | grep -q 'open files' && ulimit -n $(ulimit -Hn 2>/dev/null | head -n 1 | awk '{print $NF}')
        ;;
      * )
        ulimit -n $MAX_FD
        ;;
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # We need to detect if we are using a Windows version of Java that uses the
    # Windows path style for classpath arguments. If so, we need to convert the
    # classpath to Windows style before passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    # We need to ensure that the classpath is converted to Windows style before
    # passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    # We need to ensure that the classpath is converted to Windows style before
    # passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    # We need to ensure that the classpath is converted to Windows style before
    # passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    # We need to ensure that the classpath is converted to Windows style before
    # passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    if [ "$cygwin" = "true" ]; then
        CLASSPATH=$(cygpath --path --windows "$CLASSPATH")
    fi
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # We need to detect if we are using a Windows version of Java that uses the
    # Windows path style for classpath arguments. If so, we need to convert the
    # classpath to Windows style before passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    # We need to ensure that the classpath is converted to Windows style before
    # passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    # We need to ensure that the classpath is converted to Windows style before
    # passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    if [ "$cygwin" = "true" ]; then
        CLASSPATH=$(cygpath --path --windows "$CLASSPATH")
    fi
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # We need to detect if we are using a Windows version of Java that uses the
    # Windows path style for classpath arguments. If so, we need to convert the
    # classpath to Windows style before passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    # We need to ensure that the classpath is converted to Windows style before
    # passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    if [ "$cygwin" = "true" ]; then
        CLASSPATH=$(cygpath --path --windows "$CLASSPATH")
    fi
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # We need to detect if we are using a Windows version of Java that uses the
    # Windows path style for classpath arguments. If so, we need to convert the
    # classpath to Windows style before passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    # We need to ensure that the classpath is converted to Windows style before
    # passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    if [ "$cygwin" = "true" ]; then
        CLASSPATH=$(cygpath --path --windows "$CLASSPATH")
    fi
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # We need to detect if we are using a Windows version of Java that uses the
    # Windows path style for classpath arguments. If so, we need to convert the
    # classpath to Windows style before passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    # We need to ensure that the classpath is converted to Windows style before
    # passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    if [ "$cygwin" = "true" ]; then
        CLASSPATH=$(cygpath --path --windows "$CLASSPATH")
    fi
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # We need to detect if we are using a Windows version of Java that uses the
    # Windows path style for classpath arguments. If so, we need to convert the
    # classpath to Windows style before passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    # We need to ensure that the classpath is converted to Windows style before
    # passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    if [ "$cygwin" = "true" ]; then
        CLASSPATH=$(cygpath --path --windows "$CLASSPATH")
    fi
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H -n is not supported. Use the POSIX-compliant command 'ulimit -Hn'.
        # In POSIX sh, ulimit -n is supported, but not with the flag -n. Use the POSIX-compliant command 'ulimit -n'.
        # Also, the order of the options matters: if we use -n first, it sets the soft limit; if we use -H first, it sets the hard limit.
        # The 'head' command is used to ensure we only output the first line, as some systems may output multiple lines.
        # The 'grep' command is used to ensure we only output lines that contain the word 'open files'.
        # This is necessary because on some systems, ulimit -n may output a message about the limit being unlimited.
        # We use '2>/dev/null' to suppress error messages.
        ulimit -Hn 2>/dev/null | grep -q 'open files' && ulimit -n $(ulimit -Hn 2>/dev/null | head -n 1 | awk '{print $NF}')
        ;;
      * )
        ulimit -n $MAX_FD
        ;;
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # We need to detect if we are using a Windows version of Java that uses the
    # Windows path style for classpath arguments. If so, we need to convert the
    # classpath to Windows style before passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    # We need to ensure that the classpath is converted to Windows style before
    # passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    # We need to ensure that the classpath is converted to Windows style before
    # passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    if [ "$cygwin" = "true" ]; then
        CLASSPATH=$(cygpath --path --windows "$CLASSPATH")
    fi
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # We need to detect if we are using a Windows version of Java that uses the
    # Windows path style for classpath arguments. If so, we need to convert the
    # classpath to Windows style before passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    # We need to ensure that the classpath is converted to Windows style before
    # passing it to Java.
    # The 'cygpath' command can be used to do this.
    # The '-w' flag converts the path to Windows style.
    # The '-p' flag is used to indicate that the path is a classpath.
    if [ "$cygwin" = "true" ]; then
        CLASSPATH=$(cygpath --path --windows "$CLASSPATH")
    fi
fi

exec "$JAVACMD" \
  $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
